# Generated by Django 4.0.4 on 2024-03-21 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventsapi', '0002_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eventsapi.event'),
        ),
    ]
